In [290]:
import pandas as pd
import numpy as np

In [291]:
df = pd.read_csv("supershops.csv")
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [292]:
df.shape

(50, 5)

In [293]:
x = df.drop('Profit', axis=1)
y = df['Profit']

In [294]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [295]:
x.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [296]:
x2 = x.copy()
x_manual = x.copy()

In [297]:
x2.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [298]:
x_manual.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

# Normalization

In [299]:
from sklearn.preprocessing import MinMaxScaler

In [300]:
m = MinMaxScaler() #feature_range=(0, 1)

In [301]:
df_mar_sp = m.fit(x[['Marketing Spend']]) #calculating
df_mar_sp

MinMaxScaler()

In [302]:
x.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [303]:
x['Marketing Spend'] = m.transform(x[['Marketing Spend']])

In [304]:
x['Marketing Spend'].head()

0    0.692617
1    0.983359
2    0.927985
3    0.873136
4    0.859438
Name: Marketing Spend, dtype: float64

### For "Administration" column

In [305]:
m.fit(x[["Administration"]])

MinMaxScaler()

In [306]:
m.data_range_

array([131362.42])

In [307]:
m.data_min_

array([51283.14])

In [308]:
m.data_max_

array([182645.56])

In [309]:
x["Administration"] = m.transform(x[["Administration"]])
x.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.651744  471784.10    Dhaka
1         0.983359        0.761972  443898.53      Ctg
2         0.927985        0.379579  407934.54  Rangpur
3         0.873136        0.512998  383199.62    Dhaka
4         0.859438        0.305328  366168.42  Rangpur

In [310]:
m.fit(x[["Transport"]])

MinMaxScaler()

In [311]:
m.data_max_

array([471784.1])

In [312]:
m.data_min_

array([0.])

In [313]:
m.data_range_

array([471784.1])

In [314]:
x["Transport"] = m.transform(x[["Transport"]])
x.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.651744   1.000000    Dhaka
1         0.983359        0.761972   0.940893      Ctg
2         0.927985        0.379579   0.864664  Rangpur
3         0.873136        0.512998   0.812235    Dhaka
4         0.859438        0.305328   0.776136  Rangpur

In [315]:
x['Marketing Spend'].dtype

dtype('float64')

In [316]:
x.dtypes

Marketing Spend    float64
Administration     float64
Transport          float64
Area                object
dtype: object

# <b style="color:red">Home Work</b> ♨️♨️♨️
- using loop to apply normalization on every column

In [317]:
#Loop

# using loop to apply normalization on every column
for column in x2.columns:
    if x2[column].dtype == object:
        continue
    else:
        m.fit(x2[[column]])
        x2[column] = m.transform(x2[[column]])
x2.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.651744   1.000000    Dhaka
1         0.983359        0.761972   0.940893      Ctg
2         0.927985        0.379579   0.864664  Rangpur
3         0.873136        0.512998   0.812235    Dhaka
4         0.859438        0.305328   0.776136  Rangpur

In [318]:
x.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.651744   1.000000    Dhaka
1         0.983359        0.761972   0.940893      Ctg
2         0.927985        0.379579   0.864664  Rangpur
3         0.873136        0.512998   0.812235    Dhaka
4         0.859438        0.305328   0.776136  Rangpur

In [319]:
x['Marketing Spend'].min()

0.0

In [320]:
x['Marketing Spend'].max()

1.0

In [321]:
x['Marketing Spend'].min()

0.0

In [322]:
#do manually

In [323]:
x_manual_normalization = x_manual.copy()
x_manual_normalization.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [324]:
def normalizer(x):
    """the argument must be ndarray type"""
    minimum = x.min()
    maximum = x.max()
    return (x - minimum) / (maximum - minimum)

In [325]:
x_manual_normalization['Marketing Spend'] = normalizer(x_manual_normalization['Marketing Spend'])
x_manual_normalization.head()

Marketing Spend  Administration  Transport     Area
0         0.692617       136897.80  471784.10    Dhaka
1         0.983359       151377.59  443898.53      Ctg
2         0.927985       101145.55  407934.54  Rangpur
3         0.873136       118671.85  383199.62    Dhaka
4         0.859438        91391.77  366168.42  Rangpur

In [326]:
x_manual_normalization['Administration'] = normalizer(x_manual_normalization['Administration'])
x_manual_normalization.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.651744  471784.10    Dhaka
1         0.983359        0.761972  443898.53      Ctg
2         0.927985        0.379579  407934.54  Rangpur
3         0.873136        0.512998  383199.62    Dhaka
4         0.859438        0.305328  366168.42  Rangpur

In [327]:
x_manual_normalization['Transport'] = normalizer(x_manual_normalization['Transport'])
x_manual_normalization.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.651744   1.000000    Dhaka
1         0.983359        0.761972   0.940893      Ctg
2         0.927985        0.379579   0.864664  Rangpur
3         0.873136        0.512998   0.812235    Dhaka
4         0.859438        0.305328   0.776136  Rangpur

# Standard Scaler

In [328]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [329]:
x2['Marketing Spend'].std()

0.27760797440996104

In [330]:
x2['Marketing Spend'].mean()

0.4458540809390067

# <b style="color:red">Home Work</b> ♨️♨️♨️
- Standard Scaler

In [331]:
#do manually
x_manual.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [332]:
x_manual['Marketing Spend'].std()

45902.25648230753

In [333]:
x_manual_standardization = x_manual.copy()
x_manual_standardization.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [334]:
def standardize(x):
    mean = x.mean()
    std = x.std()
    
    return (x - mean)/ std

In [335]:
x_manual_standardization['Marketing Spend'] = standardize(x_manual_standardization['Marketing Spend'])
x_manual_standardization.head()

Marketing Spend  Administration  Transport     Area
0         0.888889       136897.80  471784.10    Dhaka
1         1.936203       151377.59  443898.53      Ctg
2         1.736731       101145.55  407934.54  Rangpur
3         1.539157       118671.85  383199.62    Dhaka
4         1.489812        91391.77  366168.42  Rangpur

In [336]:
x_manual_standardization['Administration'] = standardize(x_manual_standardization['Administration'])
x_manual_standardization.head()

Marketing Spend  Administration  Transport     Area
0         0.888889        0.555117  471784.10    Dhaka
1         1.936203        1.071924  443898.53      Ctg
2         1.736731       -0.720938  407934.54  Rangpur
3         1.539157       -0.095396  383199.62    Dhaka
4         1.489812       -1.069066  366168.42  Rangpur

In [337]:
x_manual_standardization['Transport'] = standardize(x_manual_standardization['Transport'])
x_manual_standardization.head()

Marketing Spend  Administration  Transport     Area
0         0.888889        0.555117   2.143079    Dhaka
1         1.936203        1.071924   1.910049      Ctg
2         1.736731       -0.720938   1.609511  Rangpur
3         1.539157       -0.095396   1.402811    Dhaka
4         1.489812       -1.069066   1.260487  Rangpur

In [338]:
#sklearn
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()

In [339]:
x_standardization = x_manual.copy()
x_standardization.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [340]:
for column in x_standardization.columns:
    if x_standardization[column].dtype == object:
        continue
    else:
        standardScaler.fit(x_standardization[[column]])
        x_standardization[column] = standardScaler.transform(x_standardization[[column]])
x_standardization.head()

Marketing Spend  Administration  Transport     Area
0         0.897913        0.560753   2.165287    Dhaka
1         1.955860        1.082807   1.929843      Ctg
2         1.754364       -0.728257   1.626191  Rangpur
3         1.554784       -0.096365   1.417348    Dhaka
4         1.504937       -1.079919   1.273550  Rangpur

# Robust

# <b style="color:red">Home Work</b> ♨️♨️♨️
- Robust Scaler

In [341]:
x_robustScaler = x_manual.copy()
x_robustScaler.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [342]:
from sklearn.preprocessing import RobustScaler
robustScaler = RobustScaler()

In [343]:
for column in x_robustScaler.columns:
    if x_robustScaler[column].dtype == object:
        continue
    else:
        robustScaler.fit(x_robustScaler[[column]])
        x_robustScaler[column] = robustScaler.transform(x_robustScaler[[column]])
x_robustScaler.head()

Marketing Spend  Administration  Transport     Area
0         0.672530        0.345355   1.552016    Dhaka
1         1.452113        0.697565   1.383714      Ctg
2         1.303634       -0.524290   1.166654  Rangpur
3         1.156567       -0.097977   1.017368    Dhaka
4         1.119836       -0.761543   0.914576  Rangpur

In [344]:
x_robustscaler_manual = x_manual.copy()
x_robustscaler_manual.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [345]:
def robustScaler(x):
    quantiles = np.quantile(x, [.25, .50, .75])
    Q1 = quantiles[0]
    median = quantiles[1]
    Q2 = quantiles[2]
    
    return (x - median)/(Q2 - Q1)

In [346]:
x_robustscaler_manual['Marketing Spend'] = robustScaler(x_robustscaler_manual['Marketing Spend'])
x_robustscaler_manual.head()

Marketing Spend  Administration  Transport     Area
0         0.672530       136897.80  471784.10    Dhaka
1         1.452113       151377.59  443898.53      Ctg
2         1.303634       101145.55  407934.54  Rangpur
3         1.156567       118671.85  383199.62    Dhaka
4         1.119836        91391.77  366168.42  Rangpur

In [347]:
x_robustscaler_manual['Administration'] = robustScaler(x_robustscaler_manual['Administration'])
x_robustscaler_manual.head()

Marketing Spend  Administration  Transport     Area
0         0.672530        0.345355  471784.10    Dhaka
1         1.452113        0.697565  443898.53      Ctg
2         1.303634       -0.524290  407934.54  Rangpur
3         1.156567       -0.097977  383199.62    Dhaka
4         1.119836       -0.761543  366168.42  Rangpur

In [348]:
x_robustscaler_manual['Transport'].isna().any()

True

In [349]:
x_robustscaler_manual.isna().sum()

Marketing Spend    0
Administration     0
Transport          1
Area               0
dtype: int64

# Max Abs

# <b style="color:red">Home Work</b> ♨️♨️♨️

In [350]:
from sklearn.preprocessing import MaxAbsScaler
mas = MaxAbsScaler()

In [351]:
x_max_abs_scaler = x_manual.copy()
x_max_abs_scaler.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [352]:
for column in x_max_abs_scaler.columns:
    if x_max_abs_scaler[column].dtype == object:
        continue
    else:
        mas.fit(x_max_abs_scaler[[column]])
        x_max_abs_scaler[column] = mas.transform(x_max_abs_scaler[[column]])
x_max_abs_scaler.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.749527   1.000000    Dhaka
1         0.983359        0.828805   0.940893      Ctg
2         0.927985        0.553781   0.864664  Rangpur
3         0.873136        0.649738   0.812235    Dhaka
4         0.859438        0.500378   0.776136  Rangpur

In [353]:
x_mas_manual = x_manual.copy()
x_mas_manual.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [355]:
def max_absolute_scaler(x):
    maximum = x.max()
    return x/abs(maximum)

In [356]:
x_mas_manual['Marketing Spend'] = max_absolute_scaler(x_mas_manual[['Marketing Spend']])
x_mas_manual.head()

Marketing Spend  Administration  Transport     Area
0         0.692617       136897.80  471784.10    Dhaka
1         0.983359       151377.59  443898.53      Ctg
2         0.927985       101145.55  407934.54  Rangpur
3         0.873136       118671.85  383199.62    Dhaka
4         0.859438        91391.77  366168.42  Rangpur

In [357]:
x_mas_manual['Administration'] = max_absolute_scaler(x_mas_manual[['Administration']])
x_mas_manual.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.749527  471784.10    Dhaka
1         0.983359        0.828805  443898.53      Ctg
2         0.927985        0.553781  407934.54  Rangpur
3         0.873136        0.649738  383199.62    Dhaka
4         0.859438        0.500378  366168.42  Rangpur

In [358]:
x_mas_manual['Transport'] = max_absolute_scaler(x_mas_manual[['Transport']])
x_mas_manual.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.749527   1.000000    Dhaka
1         0.983359        0.828805   0.940893      Ctg
2         0.927985        0.553781   0.864664  Rangpur
3         0.873136        0.649738   0.812235    Dhaka
4         0.859438        0.500378   0.776136  Rangpur